### PR TITLE
Update ja.json Improvement of Japanese translation

### PR DESCRIPTION
**Pull request by satopian**
```
"Tool options": "ツールオプション",
    "Brush size": "ブラシサイズ",
    "Opacity": "不透明度",
    "Color": "色補充", 
    "Blend": "混色",
    "Spacing": "間隔",
    "Scattering": "散乱",
    "Smoothing": "手ぶれ補正",

```
Translated the tool option item "color" to "色補充".  
However, hsv's color picker palette is
I want to translate it as "カラー".
The "カラー" is the Japanese of the English word "color".

### CODE REVIEW

**Comment by sakots** [comment]
This one is very important
because many of my translations were word-for-word translations of parts of the text that I had not actually used.

**Comment by thenickdude** [comment]
That sounds good about the adjustment of "Color", should I make that change too?

**Comment by satopian** [comment]
image
I checked the paint apps I use often.
ChickenPaint's "color" is
In that app
It was "color amount".

**Comment by thenickdude** [comment]
Screen Shot 2021-05-19 at 6 24 58 PM

I've updated the translation now to make it look like this

**Comment by satopian** [comment]
Thank you for adopting the translation.

**Pull request merged**
