### PR TITLE
add missing icons

### PR DESCRIPTION
**Pull request by blurymind**
This pr adds the missing icons (using ones from Gimp's similar set)
 
image

fixes https://github.com/thenickdude/chickenpaint/issues/6

### CODE REVIEW

**Comment by thenickdude** [comment]
I don't see any licensing information here

**Comment by blurymind** [comment]
it uses from gimp
https://gitlab.gnome.org/GNOME/gimp/blob/master/icons/Symbolic/symbolic-scalable.svg

not sure what the license is, guessing its creative commons

**Comment by thenickdude** [comment]
We cannot just steal icons without ensuring the license is compatible and that they are credited correctly.

**Comment by blurymind** [comment]
Would you be open to using them if I find you the license?

**Comment by thenickdude** [comment]
No, I don't think any of these icons are great fits to be honest. They're less clear than the original text. e.g. water colour just looks like a generic paintbrush, a paint roller is not a blender, undo/redo look like rotation buttons, no way to understand that the 100% zoom button will zoom to 100% based on what the icon looks like, etc.

**Comment by blurymind** [comment]
Ah fair enough. I will try to find a better set and first pitch it before
trying it in chickenpaint.

**Pull request closed without merging**
